all:
  hosts:
  children:
    labhosts:
      hosts:
        192.168.1.83:
  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: srw134
    ansible_password: PassWord!
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: PassWord!