---
- name: "INSTALL AND CONFIGURE WORDPRESS"
  hosts: "labhosts"
  vars:
    apache_user: www-data
    apache_group: www-data
  gather_facts: no
  become: True
  tasks:
    - name: "INSTALL MYSQL"
      apt: name=mysql-server update_cache=yes

    - name: "INSTALL WORDPRESS"
      apt: name=wordpress

    - name: "COPY SPECIFIC CONFIGURATION"
      copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
      notify:
      - RESTART APACHE

    - name: CHANGE FILE/DIRECTORY OWNER TO WWW-DATA
      ansible.builtin.file:
        path: /usr/share/wordpress
        owner: "{{  apache_user }}"
        group: "{{  apache_group }}"
        recurse: yes

  handlers:
    - name: RESTART APACHE
      ansible.builtin.service:
        name: apache2
        state: restarted
