
###Needs to be edited to meet our requirements

---
- name: "Router Check"
  hosts: "labhosts"
  gather_facts: no
  tasks:

    - name: Wait for system to become reachable
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started

    - name: "LOAD CONFIG VARIABLES"
      include_vars:
        file: "{{ inventory_hostname }}_vars.yaml"
        name: "router_config"
      delegate_to: "localhost"

    - name: "COLLECT FACTS INFORMATION"
      ios_facts:
        gather_subset: "all"

    - name: "CONFIRM INTERFACES ARE ENABLED"
      assert:
        that:
          - "interface['value']['lineprotocol'] == 'up'"
          - "interface['value']['operstatus'] == 'up'"
        fail_msg: "Interface {{ interface['key'] }} is DOWN"
        success_msg: "Interface {{ interface['key'] }} is UP"
      when: "interface['key'] in router_config['Interfaces'].keys() | list"
      loop: "{{ ansible_facts['net_interfaces'] | dict2items  }}"
      loop_control:
        loop_var: "interface"